const ShopActionTypes = {
    FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',

    FETCH_PLANTS_SUCCESS: "FETCH_PLANTS_SUCCESS",
    FETCH_STEMS_SUCCESS: "FETCH_STEMS_SUCCESS"
};

export default ShopActionTypes;
  